#!/bin/bash

echo "🚀 設定 Railway 環境變數..."
echo ""
echo "請在 Railway Dashboard 中手動添加以下環境變數："
echo ""
echo "=========================================="
echo "GOOGLE_CLIENT_ID=506910907793-5qt0..."
echo "GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo "GOOGLE_REDIRECT_URI=https://gmail-mcp-gateway-production.up.railway.app/auth/google/callback"
echo "SUPABASE_URL=your_supabase_url_here"
echo "SUPABASE_ANON_KEY=your_supabase_anon_key_here"
echo "NODE_ENV=production"
echo "PORT=3000"
echo "=========================================="
echo ""
echo "📝 設定步驟："
echo "1. 前往 Railway Dashboard"
echo "2. 選擇您的專案"
echo "3. 點擊 Variables 標籤"
echo "4. 添加上述環境變數"
echo "5. 保存設定"
echo ""
echo "✅ 完成後，您的應用就可以運行了！"

